export enum PagesName {
  LOGIN = "Login",
  REGISTER = "Register",
  MAIN_MENU = "Main Menu",
  LOGOUT = "Logout",
  EXIT = "Exit",
  SEARCH = "Search",
  ADMIN_MENU = "Admin Menu",
  VIEW_APIS = "View Apis",
  VIEW_APIS_DETAIL = "View Apis Detail",
  EDIT_APIS_DETAIL = "Edit Apis Detail",
  ADD_CATEGORY = "Add Category",
  USER_MENU = "User Menu",
  SEARCH_ARTICLES = "Search Articles",
  VIEW_SAVED_ARTICLES = "View Saved Articles",
  SAVE_ARTICLE = "Save Article",
  UNSAVE_ARTICLE = "Unsave Article",
}
